### ISSUE TITLE
please update the mirror

### ISSUE THREAD

**Issue by return42** [docutils/docutils#1]
Hi David, thanks for this mirror!

I'am happy to see that you serve a mirror of your awesome docutils project on github. Actually there are some commits on the svn trunk, nothing important, but anyway, could you update this mirror at regular intervals?

With best regards --Markus--

**Comment by leycec** [comment]
**I and my hamster concur.** :hamster: 

Perhaps more critically, would it be feasible to permanently migrate Docutils from Sourceforge to GitHub? I note [this gist](https://gist.github.com/tony/c5ebdc02a5c58e34956d), suggesting a great deal of well-documented thought has already been invested into this topic. It'd be a demonstrable shame to discard that transitional effort – especially given the moribund, ineffectual, and frankly antiquated state of "modern" Sourceforge. <sup>_The cancer must be purged before it spreads._</sup>

In any case, Docutils remains awesome. The continued lack of [inline nesting support](http://docutils.sourceforge.net/FAQ.html#id43) _is_ discouraging, but... superb work all around nonetheless.

**Comment by gagern** [comment]
I created a git svn clone of the docutils codebase today, and only afterwards found this repo as a source I might clone and update. Note that [my fork](https://github.com/gagern/docutils) is not only more up to date, it also includes branches and tags which are missing in this one here. Right now I don't have any automated means of updating my branch, though, so it might become outdated over time, too. Maybe I'll add automatic updates one day, but for now please let the maintainers take the lack of it as incentive to move over to GitHub for good.

Here is how I created my branches and tags:

```sh
for i in $(find .git/svn/refs -name index | grep /tags/ | cut -d/ -f7); do
    git tag "$i" "refs/remotes/origin/tags/$i"
done
for i in $(find .git/svn/refs -name index | grep -v /tags/ | cut -d/ -f6); do
    git branch "$i" "refs/remotes/origin/$i"
done
git push gagern --all
git push gagern --tags
```

**Comment by flying-sheep** [comment]
I also think that this mirror should be one level deeper, i.e.  docutils, prest, sandbox, and web should be different projects under the “docutils” organization.

And yes: migration to github or gitlab or so would greatly help community involvement.

**Comment by return42** [comment]
FYI: There is an official git mirror at   https://repo.or.cz/w/docutils.git

See also:

- http://docutils.sourceforge.net/docs/dev/repository.html#creating-a-local-git-clone
- https://sourceforge.net/p/docutils/feature-requests/58/#6423

**Comment by chrisjsewell** [comment]
See also https://github.com/chrisjsewell/docutils

**Comment by chrisjsewell** [comment]
Hey @ericholscher, as discussed in https://sourceforge.net/p/docutils/feature-requests/58 if you want to give me maintainer access here, I can look into porting the work I've done in https://github.com/chrisjsewell/docutils to here

**Comment by chrisjsewell** [comment]
thanks 😄

**Comment by ericholscher** [comment]
I'm happy to give anyone access if there's a plan to actually use it :)

**Comment by AA-Turner** [comment]
Cross-posting from the other thread -- @ericholscher please would you invite me to the org as an owner? I think that would give me all the needed permissions.

A

**Comment by AA-Turner** [comment]
For now, I've updated to r9070. When the conversion happens, we will likely wipe out this repo entirely and all history, so I'm closing this issue for now.

A

**Comment by return42** [comment]
@AA-Turner thanks! .. I opened this issue in 2016 in the meantime many things had been changed ..

> When the conversion happens

Are there any plans to move official https://docutils.sourceforge.io to https://github.com/docutils/docutils ?

**Comment by AA-Turner** [comment]
https://sourceforge.net/p/docutils/feature-requests/58/?page=2#d78b/47dd (though note it is a slow process, we're currently focussing on the 0.19.0 release).

A

**Comment by return42** [comment]
> https://sourceforge.net/p/docutils/feature-requests/58/?page=2#d78b/47dd (though note it is a slow process, we're currently focussing on the 0.19.0 release).

Thanks! Would be great to have docutils at one of the git hoster :+1: .. Often I thought I can contribute to docutils but sourceforge.net was always the reason why I did not do it after all.
